<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Apex" />
    <title>Apex Technologies</title>
    <link href="css/style.css" rel="stylesheet" />
  </head>
  <body>
    <header>
      <div class="hero-image">
        <a href="index.php">
          <img src="images/logo.png" alt="Company Logo" />
        </a>
      </div>
      <nav>
        <ul>
          <li><a href="index.php">Home</a></li>
          <li><a href="jobs.php">Job Descriptions</a></li>
          <li><a href="apply.php">Apply</a></li>
          <li><a href="about.php">About</a></li>
          <li><a href="manage.php">Manage</a></li>
          <li><a href="managejobs.php">Manage Jobs</a></li>
          <li><a href="phpenhancement.php">PHP Enhancements</a></li>
        </ul>
      </nav>
    </header>
  </body>
</html>
